<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Last_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Of_Birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Seen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Message" Member="Messages" ThisKey="Id" OtherKey="Receiver_Id" Type="Message" />
      <Association Name="User_Message1" Member="Messages1" ThisKey="Id" OtherKey="Sender_Id" Type="Message" />
      <Association Name="User_Friend" Member="Friends" ThisKey="Id" OtherKey="Friend_Id" Type="Friend" />
      <Association Name="User_Friend1" Member="Friends1" ThisKey="Id" OtherKey="User_Id" Type="Friend" />
      <Association Name="User_File" Member="Files" ThisKey="Id" OtherKey="Receiver_id" Type="File" />
      <Association Name="User_File1" Member="Files1" ThisKey="Id" OtherKey="Sender_Id" Type="File" />
      <Association Name="User_PublicMessage" Member="PublicMessages" ThisKey="Id" OtherKey="User_Id" Type="PublicMessage" />
      <Association Name="User_PublicFile" Member="PublicFiles" ThisKey="Id" OtherKey="User_Id" Type="PublicFile" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sender_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Receiver_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Member="Message1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="User" ThisKey="Receiver_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="User1" ThisKey="Sender_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Friends" Member="Friends">
    <Type Name="Friend">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Friend_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Friend" Member="User" ThisKey="Friend_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Friend1" Member="User1" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Sender_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Receiver_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="File_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="File_Path" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="File_Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_File" Member="User" ThisKey="Receiver_id" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_File1" Member="User1" ThisKey="Sender_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicMessages" Member="PublicMessages">
    <Type Name="PublicMessage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Data_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_PublicMessage" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PublicFiles" Member="PublicFiles">
    <Type Name="PublicFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="User_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="File_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="File_Path" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="File_Type" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Date_Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_PublicFile" Member="User" ThisKey="User_Id" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>